extends "res://ui/cutscenes/DialogueCutscene.gd"


func get_dialogue_json_filename() -> String:
	return "res://text/autogenerated/dialogue_%s_post_battle.json" % chapter_data.title.to_lower()


func _skip_dialogue() -> void:
	if not is_dialogue_skipped:
		is_dialogue_skipped = true
		
		if Loader.change_scene("res://ui/cutscenes/SupportSelectionMenu.tscn", chapter_data) != OK:
			printerr("Failed to change scene")

		set_process(false)
